apiVersion: apps/v1
kind: Deployment
metadata:
  name: banco
  labels:
    app: banco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banco
  template:
    metadata:
      labels:
        app: banco
    spec:
      containers:
      - name: banco
        image: banco:1.0
        resources:
          requests:
            memory: "512M"
            cpu: "500m"
          limits:
            memory: "1024M"
            cpu: "500m"
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 70
          periodSeconds: 15
          timeoutSeconds: 3
          successThreshold: 2
          failureThreshold: 2
          httpGet:
            path: /actuator/health
            port: 8080
        livenessProbe:
          initialDelaySeconds: 80
          periodSeconds: 15
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            path: /actuator/health
            port: 8080